<?php

try {
$db = new PDO('mysql:dbname=azurefennec478_twitter;host=mysql634.db.sakura.ne.jp;charset=utf8','azurefennec478','Iojk3231');
echo "接続OK!!!！";

//need_to_like_usersテーブルにtweetidカラムを追加したときのSQLコマンド
// $stmt=$db->prepare('ALTER TABLE accounts ADD accountid VARCHAR(20) AFTER twitterid');
// $stmt->execute();
// exit;


$tablenames=[
	// 'accounts',
  		// 'shimaumaen',
// 		'Tenkue_official',
// 		'totowaenjineer',
// 		'ajgmeja',
// 		'kimura9438',
// 		'tnluck1',
// 		'YukihiroLaravel',
// 		'hiro_businessX',
// 		'meteo_webteam',
// 		'hmgchk',
// 		'nishiji2525',
// 		'ym1aFv7DvKfgcjw',
// 		'atsushi_funbiz',
// 		'TSUTAYA00000926',
// 		'kakedashiman1',
// 		'WebEngrChildren',
// 		'kenji7157',
// 		'jun_kgw',
// 		'kozumaD2C',
// 		'investortat',
// 		'JiJi_web',
// 		'HospitDesign',
// 		'MoRi_Coding',
// 		'rikipage_com',
// 		'road_of_web',
// 		'kana_site',
// 		'Chil_Dreamer',
//   		'dokugaku_hard',
// 		'Saki__marke',
// 		'cwhowto',
// 		'akira_papa_IT',
// 		'okutaro247',
// 		'tradediary500',
// 		'yuji_sgs_prog',
// 		'kotukotu100man',
// 		'Chiyo_vjdaisuki',
// 		'norilog4',
// 		'mybrain20066528',
// 		'Mitsuru_Web',
// 		'himeo_design',
// 		'yuika_web06',
// 		'yuu_a_prog',
// 		'coach_kessy',
// 		'kochan0218',
// 		'tooru_medemi',
// 		'noga_design',
// 		'yuhei_design',
// 		'taka64321568',
// 		'taisyoblog',
// 		'buppanlove',
// 		'kimi_shimony',
// 		'ujihiro_web',
// 		'FreeeRoom',
//     'closer_tokyo',
// 	'iOS63069960',
// 	'akibro_mama',
// 	'Ken_FSKL',
// 	'uv6r_i',
// 	'batchgooma',
// 	'ryoblog2020',
// 	'tatsutsublog',
// 	'amusai00blog',
// 	'todai_story',
// 	'note_yuru',
// 	'ryoseiblog',
// 	'___Satoyan___',
// 	'hutaaisakihime',
// 	'omgu_r_ec0d',
// 	'take_19840618',
// 	'neru_blog',
// 	'fukuwazacom',
// 	'bambinalife',
//   'shun_webdesign',
// 	'omiyawebdesign',
// 	'yuyudora622',
// 	'kaikei_shop',
// 	'freeworkkoba',
// 	'takara_journey',
// 	'willblog13',
// 	'Kurumiiistone',
// 	'jun_sns12',
// 	'miyabi_webcss',
// 	'hilosiva',
// 	'ktktshowtaaa',
// 	'zumi_semi',
// 	'_engawatabetai',
// 	'hayato_marked',
// 	'Investor_lio',
// 	'rakutokoon',
// 	'kindlef2',
// 	'Katame_Blog',
//   'MIKI_migratory',
// 	'Omaoma2140',
// 	'kjrkrn',
// 	'yamakou_100',
// 	'servant_style',
// 	'Uryy_502',
// 	'takusukurain',
// 	'baachi_chiba',
// 	'kenny_freelife',
// 	'kiyokari1',
//   'Smallchamber25',
// 		'mad365day',
// 		'nanashi_markter',
// 		'_yoneco',
// 		'itochinkids',
// 		'nayuta_sora2021',
// 		'saison_program',
// 		'ORUrivolder',
// 		'teeetsuya0314',
// 		'YukiyoCatLove',
// 		'rapasuke_web',
// 		'icobitcoinxem',
// 		'YuichiKageyama1',
// 		'Katame_blog',
// 		'deer_garage',
// 		'taketenbai88',
// 		'ryosei_ptworks',
// 		'techstock_int',
// 		'samaramas',
// 		'aws_TakS07',
// 		'hiroyuki_ymd',
// 		'RI_consul',
// 		'ticketnote_dev',
// 		'learning0731',
// 		'shuji65349628',
// 		'mio_0821_design',
// 		'arika_technavi',
// 		'fulltimesurfer',
// 		'westhouse_k',
// 		'kunigami_takaya',
// 		'start_up_2022',
// 		'fumiya238388',
// 		'apollonlog',
//7月20日追加
		// 'nori_marketing',
//8月11日追加
		// 'sigmabi',
		// '82tech',
		// 'kmys_work',
		// 'erestage',
		// 'pointincomeinfo',
		// 'Ryu7ohhp',
		// 'RubiconLink',
		// 'toyotomi_y311',
		// 'fujikou25',
		// 'pirori_2020',
		// 'Freelanceworkjp',
		// 'bita02161704',
		// 'ec_sherlock',
		// 'BRAVO_sense',
		// 'web_onigiri',
		// 'kodayan1002',
		// 'matsumatsu04',
		// 'shiba_program',
		// 'TATSUO_NODA',
		// 'ashitanosekisan',
		// 'prest_blog',
		// 'siisoumulcre',
		// 'engineer_8800',
		// 'moromi_design',
		// 'johngineerr',
		// 'takashi_uebu',
		// '_kato_shinya',
		// 'GabakuG',
		// 'RailsRubyMah6h',
		// 'kobitoCode',
		// 'gakushi0130',
    // 'kira_python',
    // 'Roy_blog',
    // 'td03109',
    // 'RubyPHP2',
    // 'shuzo_books',
    // 'HayaokiLife',
    // 'copesama',
    // 'sakya_jp',
    // 'yuuki10932',
    // 'kanabun_buppan',
    // 'toyolo_official',
    // 'coach_watanabe',
    // 'Zoomishinkan',
    // 'dimyasvariant',
    // 'Yutakyoto12',
    // 'central_eng_',
    // 'isao_ownlife',
    // 'HiroseAkiraMHUS',
    // 'kotume_chan',
    // 'idh_net4all',
    // 'Robby_WebDesign',
    // 'shimi_pro',
    // '8suzuran8travel',
    // 'Moon_MSMC',
    // 'Graphy_Ae',
    // '_UPHN_',
    // 'beauty_ctbb',
    // 'harbors_sh',
    // 'phstarrion',
    'nanalog7',
  'kanae_udemy',
  'recoai_101',
  'Daibutsu_t_net',
  'saving_advisor',
  'forozou_2022',
  '2tointoin',
  'vk25f',
  '7miVzkFVofEKIAK',
  'kemablog3',
  'ottan_wotablog',
  'shapeman3127',
  'ichi3_startupW',
  'goki_consultant',
  'webukatu',
  'pokostyle1',
  'uta_honwakalife',
  'kaineko272',
  'kazukichi3110',
  'nachi_nachi8',
  'sakuraya0709',
  'hassy01210',
  'aBugr6ve91BO7J5',
  'fukugyo_sora',
  'yu_0503_2005',
  'fumiya238388',
  'iTakuX',
  'murapapafire',
  'v0250',
  'rito_zero',
  'bboy_fulufulu',
  'ryo_428_',
  '7ka_326',
  'mtutbo7',
  'Umaki11',
  'eiever__',
  'yesmanblog',
  'kaznize',
  'akg_tky',
  'zer0_ykisaragi',
  'kenta_freelance',
  'furusatojuku',
  'tokyoselfstudy',
  'goworkgirls',
  'Bs_Hachi',
  'storywriter',
  'da_i_chi_dev',
  'Tommy_irugi',
  'kazu_cat_study',
  'kamizato_design',
  'Rose02_design',
  'yushinfx',
  'pitopitomm',
  'ojibu2020',
  'AlchemistGlobal',
  'ki_tora1122',
  'oshiromandayo',
  'mi_wa_sensei',
  'guchi13646123',
  'techan48',
  'Inv_Engineer',
  'kabutarou2021',
  'chiiusagi2',
  'hayapu',
  'mamannu50',
  'achamo___n',
  'ItoAkira123',
  ];
foreach($tablenames as $tablename){
//小文字に変更
$tablename=strtolower($tablename);

// SQL作成
// $sql = 'ALTER TABLE '.$tablename.' MODIFY registry_datetime VARCHAR(20)'; //registry_datetimeカラムをdatetime型からvarcharに変更したときのsql
$sql = 'CREATE TABLE '.$tablename.' (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  twitterid VARCHAR(20),
  registry_datetime VARCHAR(20)
) engine=innodb default charset=utf8';

// SQL実行
$res = $db->query($sql);
}



} catch (PDOException $e) {
  echo 'DB接続エラー！: ' . $e->getMessage();
  exit;
}

exit;




$db = NULL;//データベース接続を解除